const BUTTON_UP       = 104;
const BUTTON_DOWN     = 105;
const BUTTON_LEFT     = 106;
const BUTTON_RIGHT    = 107;
const BUTTON_SESSION  = 108;
const BUTTON_USER1    = 109;
const BUTTON_USER2    = 110;
const BUTTON_MIXER    = 111;

const TOP_BUTTONS = [
    BUTTON_UP,
    BUTTON_DOWN,
    BUTTON_LEFT,
    BUTTON_RIGHT,
    BUTTON_SESSION,
    BUTTON_USER1,
    BUTTON_USER2,
    BUTTON_MIXER,
];
